groups:
  - name: "Essentials"
    applications:
      - name: "7-zip"
        source: "winget"
      - name: "VLC"
        source: "winget"
      - name: "Spotify"
        source: "winget"
      - name: "Microsoft PowerToys"
        source: "winget"
      - name: "Python.3.12"
        source: "winget"
  - name: "Development"
    applications:
      - name: "Visual Studio Enterprise 2022"
        source: "winget"
      - name: "Microsoft Visual Studio Code"
        source: "winget"
      - name: "CMake"
        source: "pip"
      - name: "Conan"
        source: "pip"
      - name: "Docker"
        source: "winget"
        installer: "docker-desktop"
      - name: "WSL"
        source: "wsl"
        distro: "Ubuntu"
  - name: "Communication & Productivity"
    applications:
      - name: "Slack"
        source: "winget"
      - name: "Discord"
        source: "winget"
      - name: "Everything"
        source: "winget"
      - name: "ShareX"
        source: "winget"
        configure: true
      - name: "Steam"
        source: "winget"
